branches:
  only:
  - dev
language: python
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
sudo: false
notifications:
  email: false
python:
- 3.4
before_install:
- chmod +x deploy.sh
install:
- git submodule update --init --recursive
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/conda
- export PATH="$HOME/conda/bin:$PATH"
- conda config --set always_yes yes
- conda install pyyaml
- conda info -a
- conda env create
- export PATH="$HOME/conda/envs/blog/bin:$PATH"
- conda list
script:
- make html
after_success:
- bash deploy.sh
env:
  matrix:
    secure: B05CVO8md3tiG62YZQzIzGryE1m/9MHBrn2jMPeMWnTVFp/IoCmAcd30RU/v1LamnAuRj4M/wi/7qZ3AA+LAz6ivXzY5voUsLUIdkuBmBpOx8YX2LjdhKNTku8Xv/TZEYUL6QMbaMOFYtS8tpNUoCuwjQeIyRc/7RAnW2gdsSBmwlrWhVSLrW0NakNjv5mCiWbrAgu4hlNvGquu2P5MjSaV55KypqCxr9BkOCEZkBf+woIorCBxUGxQg8bwGQZzQC3BTrsGIbX49Gi49WJtg3DMRdG+RAFhmHLvH72zKvt1MLO6Hekw3kihL/54yGEspfTm/ajSMnLx6E83rsYbkAKzq+bfywvc4gaOOLzQUWI96PiRGpx7+cTQfhCVpTsQmBsJm98eIiEc35a6iRJrKNGeOZHM8mit8oKsxGgVkVCnTvGglG7ViWjlv/3BZvYvhKwQmzDlt7JnMHt5NG1kehKObKavz8DpvqtQi6VmdbZx84JuZgFGyzbgM8mzi0hY63wEe6fRK0cfE8Y+hLWdpu4fqJsEK8bJNzVz7IHKWH+U7gz8wr8YkJMScM5fQTPcZRdsuZqjC2e+hHsj+lJtj3dulQkkTqPA7899YgZq/h1Vy89rB3uA87AOvFR5Xg2ThbdTI/mtyABqkoYl2gg44OhiLFd/CtUJDJqp5wU2ZJDk=
